# Generated by Django 3.1.7 on 2021-05-30 04:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LearnifyApp', '0002_auto_20210530_1020'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FeeReceipts',
            new_name='FeeReceipt',
        ),
    ]
