# Generated by Django 3.1.7 on 2021-05-30 04:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LearnifyApp', '0003_auto_20210530_1023'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='add_student',
            new_name='AddStudent',
        ),
    ]
