# Generated by Django 3.1.7 on 2021-05-31 16:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LearnifyApp', '0005_auto_20210530_1029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feereceipt',
            name='receipt_number',
            field=models.CharField(max_length=100000, unique=True, verbose_name='Receipt Number'),
        ),
        migrations.AlterField(
            model_name='feesstructure',
            name='year_session',
            field=models.CharField(max_length=7, unique=True, validators=[django.core.validators.RegexValidator(regex='\\d{4}-\\d{2}')], verbose_name='session (eg:-2019-20)'),
        ),
    ]
